---
name: Lint JSON Schemas

########################
# Start the job on PRs #
########################
on:
  pull_request:
    branches: [main]
    types: [ready_for_review, reopened]

###############
# Set the Job #
###############
jobs:
  validate:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Validate json files
          uses: mcandeia/json-schema-validator@v1.0.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            send_comment: true
            clear_comments: true
